### PR TITLE
Update to TinyMCE 6 and support for Nova 4

### PR DESCRIPTION
**Pull request by bashgeek**
Quite a bigger update here.

This enables support for Nova 4 (which introduces Vue 3), but breaks it for Nova 3 or lower, so it should be released in a new major version I suppose. It also supports the native dark-mode from Nova 4.

Together with that, I updated the included TinyMCE to current version 6, this will require a few config changes if anyone upgrades to it (specifically the plugins list), please see the default config included.

### CODE REVIEW

**Comment by bashgeek** [comment]
@emilianotisato I do not want to be pushy here, just a general question about this: Do you plan on merging and releasing this in the near future (or at all) or should we move on with a fork instead? Kind of a blocker for us currently :-) Thanks so much!

**Comment by emilianotisato** [comment]
@bashgeek Thanks for this PR. Give me this week to review it and release it as major version upgrade.

Planning to add cypres tests for this package soon

**Comment by bashgeek** [comment]
> @bashgeek Thanks for this PR. Give me this week to review it and release it as major version upgrade.
> 
> Planning to add cypres tests for this package soon

Sounds good, thanks!

**Comment by bashgeek** [comment]
@emilianotisato How's it looking so far? :-)

**Comment by emilianotisato** [comment]
@bashgeek I just merged under  v2 . Thanks for this and sorry for the delay, I had little to no time pass week.
I notice still not fully compatible with Nova 4 dependent fields api: https://nova.laravel.com/docs/4.0/resources/fields.html#dependent-fields

But I'll be working on that

**Pull request merged**
