### PR TITLE
Support for outl1ne/nova-translatable fields

### PR DESCRIPTION
**Pull request by miks**
- Support for outl1ne/nova-translatable fields
- Local development improvements against vendor/nova
- Added `laravel-assets` assets publishing tag

### CODE REVIEW

**Review by MohamedFayed22 — APPROVED** [review]

**Comment by wajdijurry** [comment]
@miks Any plan to merge this PR in near future?

**Comment by miks** [comment]
@wajdijurry no idea, it's uppon @emilianotisato

**Comment by emilianotisato** [comment]
Hi @wajdijurry @miks, thanks for you contributions but as indicated in the readme of the project, I'm not being able to maintain it. If some of you want to take ownership let me know

**Comment by wajdijurry** [comment]
@miks I tested your solution and works as expected with and without translation enabled on the field. Could you please update your branch from master and fix Codacy errors?

**Comment by miks** [comment]
@wajdijurry done

**Pull request merged**
